imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: critical
            handler:      buffered
        buffered:
            type: buffer
            handler: swift
        swift:
            type: swift_mailer
            from_email: fighterchamp@fighterchamp.pl
            to_email: slawomir.grochowski@gmail.com
            subject: Critical error detectd
            level: debug