app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

api_fight_list:
    path:     /api/walki
    controller: AppBundle\Controller\Api\FightController::listAction

api_fight_show:
    path:     /api/walki/{id}
    controller: AppBundle\Controller\Api\FightController::showAction
    requirements:
            id: '\d+'

api_signup_show:
    path:     /api/zapisy/{id}
    controller: AppBundle\Controller\Api\SignUpController::showAction
    requirements:
            id: '\d+'
