# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User: bcrypt
        Symfony\Component\Security\Core\User\User:
                    algorithm: bcrypt
                    cost: 12

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
                chain:
                    providers: [in_memory, our_users]
        in_memory:
            memory:
              users:
                admin:
                  password: examplePass
                  roles: 'ROLE_ADMIN'
                artur:
                  password: $2y$12$frZiNrGQPwxR7ElAkqITnegXrsYHC5E8hm3I.6GvMvJQJOhcX/h7C
                  roles: 'ROLE_ADMIN'
                darek:
                  password: $2y$12$.TRbZpiQO16bJ6xjaSeImeNKG7eE2sngeunSgzxMwzE.4pIpFo7P2
                  roles: 'ROLE_ADMIN'

        our_users:
                  entity: {class: AppBundle\Entity\User, property: email}

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticator:
                   - app.security.login_form_authenticator
                   - app.security.facebook_authenticator
                entry_point: app.security.login_form_authenticator

            logout:
              path: /logout

            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
