parameters:

services:
  _defaults:
     autowire: true
     autoconfigure: true
     public: false

  AppBundle\:
    resource: '../../src/AppBundle/*'
    exclude: '../../src/AppBundle/{Entity,Tests,Twig}'

  AppBundle\Controller\:
    resource: '../../src/AppBundle/Controller'
    public: true
    tags: ['controller.service_arguments']

  Symfony\Component\Serializer\Serializer:
    arguments: [['@AppBundle\Serializer\Normalizer\UserNormalizer', '@AppBundle\Serializer\Normalizer\FightNormalizer',
                 '@AppBundle\Serializer\Normalizer\SignUpNormalizer', '@AppBundle\Serializer\Normalizer\ClubNormalizer'],
                ["@serializer.encoder.json"]]

  app.doctrine.hash_password_listener:
    class: AppBundle\Doctrine\HashPasswordListener
    tags:
        - {name: doctrine.event_subscriber}

  app.twig_extension:
    class: AppBundle\Twig\AppExtension
    public: false

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl

  twig.extension.dyting_loader:
    class: Twig_Extension_StringLoader