# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  _defaults:
    autowire: true
    autoconfigure: true

  AppBundle\Serializer\Normalizer\UserNormalizer: ~

  normalizer.club:
        class: AppBundle\Serializer\Normalizer\ClubNormalizer

  normalizer.task:
        class: AppBundle\Serializer\Normalizer\TaskNormalizer

  serializer_club:
        class: Symfony\Component\Serializer\Serializer
        arguments: [["@normalizer.club"], ["@serializer.encoder.json"]]

  serializer_task:
        class: Symfony\Component\Serializer\Serializer
        arguments: [["@normalizer.task"], ["@serializer.encoder.json"]]

  serializer_user:
        class: Symfony\Component\Serializer\Serializer
        arguments: [["UserNormalizer"], ["@serializer.encoder.json"]]

  app.security.login_form_authenticator:
    class: AppBundle\Security\LoginFormAuthenticator

  app.security.facebook_authenticator:
    class: AppBundle\Security\FacebookAuthenticator

  app.doctrine.hash_password_listener:
    class: AppBundle\Doctrine\HashPasswordListener
    tags:
        - {name: doctrine.event_subscriber}

  AppBundle\Service\AppMailer:
    arguments: ["@mailer"]

  app.twig_extension:
          class: AppBundle\Twig\AppExtension
          public: false

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl

  twig.extension.dyting_loader:
    class: Twig_Extension_StringLoader

