# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  _defaults:
     autowire: true
     autoconfigure: true
     public: true

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
  AppBundle\:
    resource: '../../src/AppBundle/*'
    # you can exclude directories or files
    # but if a service is unused, it's removed anyway
    exclude: '../../src/AppBundle/{Entity,Repository,Tests,DataFixtures,Twig}'


  normalizer.club:
        class: AppBundle\Serializer\Normalizer\ClubNormalizer

  normalizer.task:
        class: AppBundle\Serializer\Normalizer\TaskNormalizer

  normalizer.signup:
      class: AppBundle\Serializer\Normalizer\SignUpNormalizer

  normalizer.user:
      class: AppBundle\Serializer\Normalizer\UserNormalizer

  normalizer.fight:
        class: AppBundle\Serializer\Normalizer\FightNormalizer

  normalizer.member:
        class: AppBundle\Serializer\Normalizer\MemberNormalizer

  normalizer.organization:
        class: AppBundle\Serializer\Normalizer\OrganizationNormalizer

  serializer.testing:
          class: Symfony\Component\Serializer\Serializer
          arguments: [["@normalizer.organization", "@normalizer.member"], ["@serializer.encoder.json"]]
          public: true

  serializer.my:
        class: Symfony\Component\Serializer\Serializer
        arguments: [['@normalizer.user', '@normalizer.fight', '@normalizer.signup'], ["@serializer.encoder.json"]]


  app.security.login_form_authenticator:
    class: AppBundle\Security\LoginFormAuthenticator

  app.security.facebook_authenticator:
    class: AppBundle\Security\FacebookAuthenticator

  app.doctrine.hash_password_listener:
    class: AppBundle\Doctrine\HashPasswordListener
    tags:
        - {name: doctrine.event_subscriber}

#  AppBundle\Service\AppMailer:
#    arguments: ["@mailer"]

  app.twig_extension:
          class: AppBundle\Twig\AppExtension
          public: false

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl

  twig.extension.dyting_loader:
    class: Twig_Extension_StringLoader

